# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df=pd.read_csv(
    Path("Resources/applicants_data.csv"))

# Review the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
applicant_data_df.tail()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [4]:
# Review the data types associated with the columns

applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [5]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=["EIN", "NAME"])

# Review the DataFrame
applicant_data_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [6]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == 'object'].index)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [7]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [8]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

C:\Users\eleph\anaconda3\envs\mlenv\lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [9]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names_out(categorical_variables)
)

# Review the DataFrame
encoded_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [10]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat(
    [
        applicant_data_df[["STATUS", "ASK_AMT", "IS_SUCCESSFUL"]],
        encoded_df 
    ],
    axis=1
)

# Review the Dataframe
encoded_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [11]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df["IS_SUCCESSFUL"]

# Display a sample of y
y[:5]

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [12]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=["IS_SUCCESSFUL"])

# Review the features DataFrame
X.head()

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [13]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [14]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [15]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [16]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [17]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 = (number_input_features + number_output_neurons)//2

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [18]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 = (hidden_nodes_layer1 + number_output_neurons)//2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [19]:
# Create the Sequential model instance
nn = Sequential()

In [20]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [21]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [22]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=number_output_neurons,activation="sigmoid"))

In [23]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 58)                6786

 dense_1 (Dense)             (None, 29)                1711

 dense_2 (Dense)             (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [25]:
# Compile the Sequential model
nn.compile(
    loss="binary_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

In [26]:
# Fit the model using 50 epochs and the training data
fit_model = nn.fit(
    X_train_scaled,
    y_train,
    epochs=50,
)

Epoch 1/50
804/804 [==============================] - 9s 4ms/step - loss: 0.5766 - accuracy: 0.7210
Epoch 2/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5542 - accuracy: 0.7297
Epoch 3/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5500 - accuracy: 0.7308
Epoch 4/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5482 - accuracy: 0.7322
Epoch 5/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5464 - accuracy: 0.7311
Epoch 6/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5459 - accuracy: 0.7326
Epoch 7/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5454 - accuracy: 0.7332
Epoch 8/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5432 - accuracy: 0.7336
Epoch 9/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5435 - accuracy: 0.7336
Epoch 10/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5425 - accuracy: 0.7341
Epoch 11/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5422 - accuracy: 0.7344
Epoch 12/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5416 - accuracy: 0.7359
Epoch 13/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5412 - accuracy: 0.7347
Epoch 14/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5403 - accuracy: 0.7357
Epoch 15/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5405 - accuracy: 0.7357
Epoch 16/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5402 - accuracy: 0.7362
Epoch 17/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5397 - accuracy: 0.7379
Epoch 18/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5392 - accuracy: 0.7360
Epoch 19/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5390 - accuracy: 0.7368
Epoch 20/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5380 - accuracy: 0.7367
Epoch 21/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5385 - accuracy: 0.7364
Epoch 22/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5383 - accuracy: 0.7369
Epoch 23/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5377 - accuracy: 0.7378
Epoch 24/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5378 - accuracy: 0.7376
Epoch 25/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5372 - accuracy: 0.7381
Epoch 26/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5366 - accuracy: 0.7374
Epoch 27/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5363 - accuracy: 0.7375
Epoch 28/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5364 - accuracy: 0.7386
Epoch 29/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5363 - accuracy: 0.7382
Epoch 30/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5361 - accuracy: 0.7377
Epoch 31/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5354 - accuracy: 0.7385
Epoch 32/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5354 - accuracy: 0.7382
Epoch 33/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5351 - accuracy: 0.7379
Epoch 34/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5353 - accuracy: 0.7387
Epoch 35/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5352 - accuracy: 0.7385
Epoch 36/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5350 - accuracy: 0.7387
Epoch 37/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5353 - accuracy: 0.7386
Epoch 38/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5342 - accuracy: 0.7394
Epoch 39/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5346 - accuracy: 0.7399
Epoch 40/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5345 - accuracy: 0.7386
Epoch 41/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5340 - accuracy: 0.7386
Epoch 42/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5340 - accuracy: 0.7399
Epoch 43/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5338 - accuracy: 0.7397
Epoch 44/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5338 - accuracy: 0.7396
Epoch 45/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5332 - accuracy: 0.7395
Epoch 46/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5333 - accuracy: 0.7398
Epoch 47/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5331 - accuracy: 0.7396
Epoch 48/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5333 - accuracy: 0.7397
Epoch 49/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5333 - accuracy: 0.7412
Epoch 50/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5327 - accuracy: 0.7400

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [27]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 5s - loss: 0.5522 - accuracy: 0.7306 - 5s/epoch - 17ms/step
Loss: 0.5521842837333679, Accuracy: 0.7306122183799744

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [28]:
# Set the model's file path
file_path = Path("Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [29]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [30]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [31]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = (number_input_features + number_output_neurons)// 2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

58

In [33]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [35]:
# First hidden layer
nn_A1.add(
    tf.keras.layers.Dense(
        units=hidden_nodes_layer1_A1,
        input_dim=number_input_features,
        activation="relu"
    )
)

# Output layer
nn_A1.add(
    tf.keras.layers.Dense(
        units=number_output_neurons_A1,
        activation="sigmoid"
    )
)

# Check the structure of the model
nn_A1.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 58)                6786

 dense_4 (Dense)             (None, 1)                 59

=================================================================
Total params: 6,845
Trainable params: 6,845
Non-trainable params: 0
_________________________________________________________________

In [36]:
# Compile the Sequential model
nn_A1.compile(
    loss="binary_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

In [38]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(
    X_train_scaled,
    y_train,
    epochs=50,
)

Epoch 1/50
804/804 [==============================] - 5s 4ms/step - loss: 0.5810 - accuracy: 0.7182
Epoch 2/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5575 - accuracy: 0.7273
Epoch 3/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5541 - accuracy: 0.7303
Epoch 4/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5515 - accuracy: 0.7291
Epoch 5/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5494 - accuracy: 0.7311
Epoch 6/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5485 - accuracy: 0.7314
Epoch 7/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5479 - accuracy: 0.7325
Epoch 8/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5467 - accuracy: 0.7317
Epoch 9/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5466 - accuracy: 0.7317
Epoch 10/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5454 - accuracy: 0.7316
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7345
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5442 - accuracy: 0.7335
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7329
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7332
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7335
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5435 - accuracy: 0.7342
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7349
Epoch 18/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5431 - accuracy: 0.7346
Epoch 19/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5428 - accuracy: 0.7348
Epoch 20/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5422 - accuracy: 0.7341
Epoch 21/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5422 - accuracy: 0.7353
Epoch 22/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5416 - accuracy: 0.7360
Epoch 23/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5418 - accuracy: 0.7340
Epoch 24/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5418 - accuracy: 0.7345
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7347
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7355
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7338
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7352
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7375
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7350
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7355
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7353
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7343
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7360
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7354
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7358
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7368
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7347
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7367
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7367
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7356
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7358
Epoch 43/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5384 - accuracy: 0.7362
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7364
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7370
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7356
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7358
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7362
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7364
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7364

#### Alternative Model 2

In [39]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [40]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [41]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = round((number_input_features * .6666666), 0)

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

77.0

In [49]:
# Define the number of hidden nodes for the second hidden layer

hidden_nodes_layer2_A2 = (hidden_nodes_layer1_A2 + number_output_neurons ) // 2

# Review the number of hidden nodes in the second layer

hidden_nodes_layer2_A2

39.0

In [54]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [55]:
# First hidden layer
nn_A2.add(
    tf.keras.layers.Dense(
        units=hidden_nodes_layer1_A2,
        input_dim=number_input_features,
        activation="sigmoid"
    )
)

# Second hidden layer
nn_A2.add(
    tf.keras.layers.Dense(
        units=hidden_nodes_layer2_A2,
        activation = "sigmoid"
    )
)

# Output layer
nn_A2.add(
    tf.keras.layers.Dense(
        units=number_output_neurons_A2,
        activation="sigmoid"
    )
)

# Check the structure of the model
nn_A2.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_17 (Dense)            (None, 77)                9009

 dense_18 (Dense)            (None, 39)                3042

 dense_19 (Dense)            (None, 1)                 40

=================================================================
Total params: 12,091
Trainable params: 12,091
Non-trainable params: 0
_________________________________________________________________

In [57]:
# Compile the model
nn_A2.compile(
    loss="binary_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

In [58]:
# Fit the model

fit_model_A2 = nn_A2.fit(
    X_train_scaled,
    y_train,
    epochs=200
)

Epoch 1/200
804/804 [==============================] - 2s 1ms/step - loss: 0.5956 - accuracy: 0.7020
Epoch 2/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5718 - accuracy: 0.7236
Epoch 3/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5665 - accuracy: 0.7257
Epoch 4/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5609 - accuracy: 0.7286
Epoch 5/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5554 - accuracy: 0.7287
Epoch 6/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5529 - accuracy: 0.7300
Epoch 7/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5510 - accuracy: 0.7313
Epoch 8/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5498 - accuracy: 0.7316
Epoch 9/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5481 - accuracy: 0.7308
Epoch 10/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5477 - accuracy: 0.7319
Epoch 11/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5462 - accuracy: 0.7340
Epoch 12/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5460 - accuracy: 0.7328
Epoch 13/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5453 - accuracy: 0.7330
Epoch 14/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7334
Epoch 15/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7348
Epoch 16/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5433 - accuracy: 0.7349
Epoch 17/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7348
Epoch 18/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7355
Epoch 19/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5418 - accuracy: 0.7346
Epoch 20/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5416 - accuracy: 0.7346
Epoch 21/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7361
Epoch 22/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7351
Epoch 23/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5399 - accuracy: 0.7360
Epoch 24/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5399 - accuracy: 0.7369
Epoch 25/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7362
Epoch 26/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7362
Epoch 27/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7378
Epoch 28/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5380 - accuracy: 0.7352
Epoch 29/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7368
Epoch 30/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7370
Epoch 31/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7393
Epoch 32/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7381
Epoch 33/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7373
Epoch 34/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7376
Epoch 35/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5365 - accuracy: 0.7384
Epoch 36/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5362 - accuracy: 0.7380
Epoch 37/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5361 - accuracy: 0.7376
Epoch 38/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5358 - accuracy: 0.7383
Epoch 39/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5356 - accuracy: 0.7384
Epoch 40/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7382
Epoch 41/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5353 - accuracy: 0.7399
Epoch 42/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5350 - accuracy: 0.7383
Epoch 43/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5346 - accuracy: 0.7385
Epoch 44/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5345 - accuracy: 0.7386
Epoch 45/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5344 - accuracy: 0.7390
Epoch 46/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5345 - accuracy: 0.7389
Epoch 47/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5341 - accuracy: 0.7397
Epoch 48/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5339 - accuracy: 0.7396
Epoch 49/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5336 - accuracy: 0.7399
Epoch 50/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5333 - accuracy: 0.7393
Epoch 51/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5333 - accuracy: 0.7399
Epoch 52/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5329 - accuracy: 0.7395
Epoch 53/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7396
Epoch 54/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5325 - accuracy: 0.7399
Epoch 55/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5324 - accuracy: 0.7401
Epoch 56/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5324 - accuracy: 0.7391
Epoch 57/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5322 - accuracy: 0.7413
Epoch 58/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7402
Epoch 59/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5322 - accuracy: 0.7398
Epoch 60/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5315 - accuracy: 0.7392
Epoch 61/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5314 - accuracy: 0.7413
Epoch 62/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5312 - accuracy: 0.7403
Epoch 63/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5313 - accuracy: 0.7399
Epoch 64/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5310 - accuracy: 0.7403
Epoch 65/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5306 - accuracy: 0.7407
Epoch 66/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5311 - accuracy: 0.7408
Epoch 67/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5307 - accuracy: 0.7410
Epoch 68/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5301 - accuracy: 0.7414
Epoch 69/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5307 - accuracy: 0.7409
Epoch 70/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5300 - accuracy: 0.7421
Epoch 71/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5303 - accuracy: 0.7411
Epoch 72/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5298 - accuracy: 0.7412
Epoch 73/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5298 - accuracy: 0.7418
Epoch 74/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5295 - accuracy: 0.7411
Epoch 75/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5295 - accuracy: 0.7407
Epoch 76/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5297 - accuracy: 0.7418
Epoch 77/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5293 - accuracy: 0.7400
Epoch 78/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5295 - accuracy: 0.7416
Epoch 79/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5290 - accuracy: 0.7419
Epoch 80/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5290 - accuracy: 0.7411
Epoch 81/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5290 - accuracy: 0.7423
Epoch 82/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5291 - accuracy: 0.7423
Epoch 83/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5287 - accuracy: 0.7418
Epoch 84/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5283 - accuracy: 0.7413
Epoch 85/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5288 - accuracy: 0.7414
Epoch 86/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5286 - accuracy: 0.7422
Epoch 87/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5285 - accuracy: 0.7414
Epoch 88/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5281 - accuracy: 0.7420
Epoch 89/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5282 - accuracy: 0.7413
Epoch 90/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5280 - accuracy: 0.7420
Epoch 91/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5278 - accuracy: 0.7418
Epoch 92/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5278 - accuracy: 0.7423
Epoch 93/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5278 - accuracy: 0.7422
Epoch 94/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5279 - accuracy: 0.7414
Epoch 95/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5276 - accuracy: 0.7421
Epoch 96/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5280 - accuracy: 0.7424
Epoch 97/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5273 - accuracy: 0.7420
Epoch 98/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5278 - accuracy: 0.7423
Epoch 99/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5274 - accuracy: 0.7422
Epoch 100/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5273 - accuracy: 0.7428
Epoch 101/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5274 - accuracy: 0.7423
Epoch 102/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5271 - accuracy: 0.7417
Epoch 103/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5271 - accuracy: 0.7413
Epoch 104/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5273 - accuracy: 0.7414
Epoch 105/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5271 - accuracy: 0.7421
Epoch 106/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5269 - accuracy: 0.7424
Epoch 107/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5268 - accuracy: 0.7425
Epoch 108/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5268 - accuracy: 0.7434
Epoch 109/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5267 - accuracy: 0.7426
Epoch 110/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5267 - accuracy: 0.7406
Epoch 111/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5267 - accuracy: 0.7417
Epoch 112/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5266 - accuracy: 0.7420
Epoch 113/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5264 - accuracy: 0.7427
Epoch 114/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5266 - accuracy: 0.7429
Epoch 115/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5265 - accuracy: 0.7422
Epoch 116/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5261 - accuracy: 0.7417
Epoch 117/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5263 - accuracy: 0.7419
Epoch 118/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5262 - accuracy: 0.7431
Epoch 119/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5262 - accuracy: 0.7426
Epoch 120/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5260 - accuracy: 0.7423
Epoch 121/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5260 - accuracy: 0.7421
Epoch 122/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5261 - accuracy: 0.7432
Epoch 123/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5257 - accuracy: 0.7419
Epoch 124/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5260 - accuracy: 0.7423
Epoch 125/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5259 - accuracy: 0.7434
Epoch 126/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5259 - accuracy: 0.7428
Epoch 127/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5257 - accuracy: 0.7432
Epoch 128/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5257 - accuracy: 0.7430
Epoch 129/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5257 - accuracy: 0.7424
Epoch 130/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5255 - accuracy: 0.7435
Epoch 131/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5258 - accuracy: 0.7430
Epoch 132/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5255 - accuracy: 0.7430
Epoch 133/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7429
Epoch 134/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5257 - accuracy: 0.7433
Epoch 135/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5253 - accuracy: 0.7431
Epoch 136/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5252 - accuracy: 0.7433
Epoch 137/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5254 - accuracy: 0.7435
Epoch 138/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5253 - accuracy: 0.7429
Epoch 139/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5251 - accuracy: 0.7430
Epoch 140/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5253 - accuracy: 0.7438
Epoch 141/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5252 - accuracy: 0.7435
Epoch 142/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5249 - accuracy: 0.7432
Epoch 143/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5250 - accuracy: 0.7439
Epoch 144/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5247 - accuracy: 0.7428
Epoch 145/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5247 - accuracy: 0.7431
Epoch 146/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5247 - accuracy: 0.7429
Epoch 147/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5247 - accuracy: 0.7425
Epoch 148/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5249 - accuracy: 0.7440
Epoch 149/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5248 - accuracy: 0.7426
Epoch 150/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5250 - accuracy: 0.7427
Epoch 151/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7434
Epoch 152/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5247 - accuracy: 0.7442
Epoch 153/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5249 - accuracy: 0.7434
Epoch 154/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5246 - accuracy: 0.7440
Epoch 155/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7434
Epoch 156/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5245 - accuracy: 0.7425
Epoch 157/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5244 - accuracy: 0.7438
Epoch 158/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5245 - accuracy: 0.7439
Epoch 159/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5247 - accuracy: 0.7434
Epoch 160/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5244 - accuracy: 0.7440
Epoch 161/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5243 - accuracy: 0.7442
Epoch 162/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5243 - accuracy: 0.7437
Epoch 163/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5241 - accuracy: 0.7434
Epoch 164/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5240 - accuracy: 0.7431
Epoch 165/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5240 - accuracy: 0.7442
Epoch 166/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5242 - accuracy: 0.7437
Epoch 167/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5239 - accuracy: 0.7436
Epoch 168/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5243 - accuracy: 0.7435
Epoch 169/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5239 - accuracy: 0.7437
Epoch 170/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5240 - accuracy: 0.7437
Epoch 171/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5239 - accuracy: 0.7436
Epoch 172/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5241 - accuracy: 0.7439
Epoch 173/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5238 - accuracy: 0.7444
Epoch 174/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5239 - accuracy: 0.7434
Epoch 175/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5238 - accuracy: 0.7436
Epoch 176/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5237 - accuracy: 0.7441
Epoch 177/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5237 - accuracy: 0.7443
Epoch 178/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5238 - accuracy: 0.7442
Epoch 179/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5238 - accuracy: 0.7439
Epoch 180/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5238 - accuracy: 0.7433
Epoch 181/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5237 - accuracy: 0.7454
Epoch 182/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5237 - accuracy: 0.7437
Epoch 183/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5236 - accuracy: 0.7434
Epoch 184/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5235 - accuracy: 0.7439
Epoch 185/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5235 - accuracy: 0.7434
Epoch 186/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5235 - accuracy: 0.7445
Epoch 187/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5236 - accuracy: 0.7437
Epoch 188/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5236 - accuracy: 0.7438
Epoch 189/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5236 - accuracy: 0.7437
Epoch 190/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5235 - accuracy: 0.7436
Epoch 191/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5235 - accuracy: 0.7431
Epoch 192/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5232 - accuracy: 0.7438
Epoch 193/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5233 - accuracy: 0.7445
Epoch 194/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5234 - accuracy: 0.7434
Epoch 195/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5231 - accuracy: 0.7437
Epoch 196/200

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [59]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5522 - accuracy: 0.7306 - 226ms/epoch - 843us/step
Loss: 0.5521842837333679, Accuracy: 0.7306122183799744

In [60]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 0.5561 - accuracy: 0.7301 - 325ms/epoch - 1ms/step
Loss: 0.5561167597770691, Accuracy: 0.7301457524299622

In [61]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 0.5718 - accuracy: 0.7287 - 332ms/epoch - 1ms/step
Loss: 0.5717718005180359, Accuracy: 0.7287463545799255

### Step 3: Save each of your alternative models as an HDF5 file.

In [62]:
# Set the file path for the first alternative model
file_path = Path("Resources/AlphabetSoup_A1.h5")

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [63]:
# Set the file path for the second alternative model
file_path = Path("Resources/AlphabetSoup_A2.h5")

# Export your model to a HDF5 file
nn_A2.save(file_path)